window.CERTIFICATIONS = [
  {
    id: "dp-900",
    code: "DP-900",
    name: "Microsoft Certified: Azure Data Fundamentals",
    shortName: "Azure Data Fundamentals",
    issuer: "Microsoft",
    status: "earned",
    badge: null,
    badgeAlt: "Microsoft Certified Azure Data Fundamentals badge",
    icon: "bx-data",
    accent: "#13dce7",
    earnedDate: null,
    expirationDate: null,
    credentialUrl: null,
    relatedEvidenceUrl: null,
    relatedEvidenceLabel: null,
    skills: [
      "Azure data concepts",
      "Data storage",
      "Analytics workloads"
    ]
  },
  {
    id: "ai-900",
    code: "AI-900",
    name: "Microsoft Certified: Azure AI Fundamentals",
    shortName: "Azure AI Fundamentals",
    issuer: "Microsoft",
    status: "earned",
    badge: null,
    badgeAlt: "Microsoft Certified Azure AI Fundamentals badge",
    icon: "bx-brain",
    accent: "#8164ff",
    earnedDate: null,
    expirationDate: null,
    credentialUrl: null,
    relatedEvidenceUrl: null,
    relatedEvidenceLabel: null,
    skills: [
      "Azure AI concepts",
      "Responsible AI"
    ]
  },
  {
    id: "sc-900",
    code: "SC-900",
    name: "Microsoft Certified: Security, Compliance, and Identity Fundamentals",
    shortName: "Security, Compliance, and Identity Fundamentals",
    issuer: "Microsoft",
    status: "earned",
    badge: null,
    badgeAlt: "Microsoft Certified Security, Compliance, and Identity Fundamentals badge",
    icon: "bx-shield-quarter",
    accent: "#2fdda2",
    earnedDate: null,
    expirationDate: null,
    credentialUrl: null,
    relatedEvidenceUrl: null,
    relatedEvidenceLabel: null,
    skills: [
      "Security fundamentals",
      "Compliance",
      "Identity"
    ]
  },
  {
    id: "sc-300",
    code: "SC-300",
    name: "Microsoft Certified: Identity and Access Administrator Associate",
    shortName: "Identity and Access Administrator Associate",
    issuer: "Microsoft",
    status: "earned",
    badge: null,
    badgeAlt: "Microsoft Certified Identity and Access Administrator Associate badge",
    icon: "bx-id-card",
    accent: "#5b8cff",
    earnedDate: null,
    expirationDate: null,
    credentialUrl: null,
    relatedEvidenceUrl: null,
    relatedEvidenceLabel: null,
    skills: [
      "Microsoft Entra ID",
      "Conditional Access",
      "Identity governance"
    ]
  },
  {
    id: "ccna-200-301",
    code: "CCNA 200-301",
    name: "Cisco Certified Network Associate",
    shortName: "Cisco Certified Network Associate",
    issuer: "Cisco",
    status: "in-preparation",
    badge: null,
    badgeAlt: "",
    icon: "bx-network-chart",
    accent: "#8164ff",
    earnedDate: null,
    expirationDate: null,
    credentialUrl: null,
    studyPathUrl: null,
    studyPathLabel: null,
    focus: "Networking fundamentals and infrastructure.",
    skills: []
  },
  {
    id: "sc-500",
    code: "SC-500",
    name: "Microsoft Certified: Cloud and AI Security Engineer Associate",
    shortName: "Cloud and AI Security Engineer Associate",
    issuer: "Microsoft",
    status: "in-preparation",
    badge: null,
    badgeAlt: "",
    icon: "bx-lock-alt",
    accent: "#8164ff",
    earnedDate: null,
    expirationDate: null,
    credentialUrl: null,
    studyPathUrl: null,
    studyPathLabel: null,
    focus: "Cloud and AI security across Azure and hybrid environments.",
    skills: []
  }
];
